services:
  # api:
  #   build:
  #     context: ./api
  #     dockerfile: dev.api.Dockerfile
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - MONGO_URI=mongodb://mongo:27017/gamedb
  #   depends_on:
  #     - mongo
  # web:
  #   build:
  #     context: ./web
  #     dockerfile: dev.web.Dockerfile
  #   ports:
  #     - 5173:5173
  # mongo:
  #   image: mongo:8.0-rc
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongo-data:/data/db

  gateway:

volumes:
  mongo-data:
