services:
  api:
    build:
      context: ./api
      dockerfile: dev.api.Dockerfile
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb://mongo:27017/gamedb
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: dev.frontend.Dockerfile
    ports:
      - 5173:5173

  mongo:
    image: mongo:8.0-rc
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  gateway:
    image: nginx:latest
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - frontend
      - api

volumes:
  mongo-data:
